# Generated by Django 5.2 on 2025-04-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default='', null=True),
        ),
    ]
