# Generated by Django 5.2 on 2025-04-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doctor_slug_patient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='slug',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
