# Generated by Django 5.2 on 2025-04-24 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_patient_slug_alter_doctor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
