# Generated by Django 5.2 on 2025-04-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_doctor_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
    ]
